### ISSUE TITLE
Could you please write a kotlin sample?Thank you!

### ISSUE THREAD

**Issue by JoneJay** [LiteKite/Android-MonetizeApp#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by svignesh93** [comment]
Hi @JoneJay,

I've been thinking for a while to make this sample in Kotlin. But due to its interoperability with Kotlin, it is the least priority at this time.
