### ISSUE TITLE
Where is the license public key?????And how to login in/out???

### ISSUE THREAD

**Issue by JoneJay** [LiteKite/Android-MonetizeApp#15]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by svignesh93** [comment]
Hi @JoneJay, 

Google's play billing library does not require any license key for the client app. The package name should be the same as the one that's uploaded to the play store. Please ensure you've updated your SKU KEYS for in-app and subscriptions on the monetize section of the play store and enable testing options in the settings of the play store.

The sample app does not have any login mechanism. It works only if the billing setup was successful and just need to make one-time test purchase.
